name: Publish package django!

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine

      - name: Build and Upload to PyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_API_TOKEN}}
